# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Griffin < Formula
  desc ""
  homepage ""
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/sanoyo/griffin/releases/download/v0.2.2/griffin_Darwin_x86_64.tar.gz"
      sha256 "1940f0e9150f128ab02d2d0e8cdb85a9365cb6c87f29a3cc1d43c26fe521e4e8"

      def install
        bin.install "griffin"
      end
    end
    on_arm do
      url "https://github.com/sanoyo/griffin/releases/download/v0.2.2/griffin_Darwin_arm64.tar.gz"
      sha256 "46e670c1958cc66c09e292c03ba81d473970fbbdb4c6fe798bbf53af80ce7e2d"

      def install
        bin.install "griffin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanoyo/griffin/releases/download/v0.2.2/griffin_Linux_x86_64.tar.gz"
        sha256 "15b1decf2972d9c1b32bbe33a2eae58b0d604dd97d6fcf48795298df311cd756"

        def install
          bin.install "griffin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanoyo/griffin/releases/download/v0.2.2/griffin_Linux_arm64.tar.gz"
        sha256 "7bb00e344d76354ca9222fa378dc6c15496ba74ab71023266e5be4a2e46cd41c"

        def install
          bin.install "griffin"
        end
      end
    end
  end
end
